# Project information
site_name: PyMAPE
site_url: https://elbowz.github.io/PyMAPE/
site_author: Emanuele Palombo
site_description: >-
  Software framework to support the development and deployment 
  of Autonomous (Self-Adaptive) Systems

# Repository
repo_name: elbowz/PyMAPE
repo_url: https://github.com/elbowz/PyMAPE
#edit_uri: ''  #disables edit button

# Copyright
copyright: Copyright &copy; 2022 - 2023 Emanuele Palombo

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    # - content.tooltips # Sponsors only
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
#      primary: amber
#      accent: yellow
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
#      primary: amber
#      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: simple/hive_blockchain
    repo: fontawesome/brands/github
#  logo: assets/logo.png
#  favicon: assets/favicon.png
  language: en

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pymape/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/emanuele-palombo/
    - icon: fontawesome/brands/github-alt
      link: https://github.com/elbowz/pymape

## Custom theme additions
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started.md